name: 'my_dbt_bq_demo'
version: '1.0'
config-version: 2

profile: 'my_bigquery_profile'

model-paths: ["models"]
seed-paths:   ["seeds"]
target-path:  "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_bq_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
